name: Go

on:
  push:
    paths:
      - 'engine/**'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      working-directory: engine
      run: go test -v ./...
